[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["osu_env"]

[project]
name = "osu_env"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "pre-commit",
]
